### ISSUE TITLE
Comparison to Redux

### ISSUE THREAD

**Issue by fifafu** [ngrx/store#16]
It would be great if you'd have some description on why/if using this RxJS based implementation is better suited for AngularJS 2 apps than using the standard Redux. This would be very helpful for Angular 2 & RxJS beginners like me. (Especially with the ongoing discussion about "JavaScript Fatigue")

I have successfully used Redux before with AngularJS 1 but am completely new to AngularJS2 & RxJS

Best,
Andreas

**Comment by fxck** [comment]
Well it's easy, in angular you want to use reactive programming. And redux itself is not an observable. So to get redux working, you'd have to write some sort of middleware that subscribes(http://rackt.org/redux/docs/api/Store.html#subscribe) to redux store and pushes the value to your middleware observable/subject. But why bother when pretty much all redux does is this https://github.com/ngrx/store/blob/master/src/store.ts#L83

**Comment by gsans** [comment]
I share the opinion with Andreas. I would like to see some code covering
side-by-side use cases: setup, component subscribing to updates, component
dispatching actions, component doing asynchronous tasks, etc and how it
compares to Redux (advantages/disadvantages). Cheers!

**Comment by fxck** [comment]
this is not enough https://github.com/ngrx/angular2-store-example ?

**Comment by gsans** [comment]
Sure. This is an example on how to use ngrx/store but it doesn't help a
newbie get a clear side-by-side comparison when coming from Redux and with
little knowledge on RxJS. Maybe it's material for a blog post and not docs.

**Comment by fifafu** [comment]
Yes, a blog post may be even better! I have recently seen various blog posts about how to use Redux with Angular 2, so it doesn't seem to be common knowledge that RxJS can already do almost everything Redux does...
Also I wonder if the big community & ecosystem around the original Redux will be a big advantage in the future. In general, Redux seems to be loved by many.

//edit, ah just noticed that one of the blog posts about Angular 2 & Redux was written by you @gsans :-). Thanks for that post!

**Comment by fxck** [comment]
Redux in its core is just standard `reduce()` function https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce with some fancy methods around it, ngrx/store is just standard `scan()` function http://reactivex.io/documentation/operators/scan.html (which does exactly the same as `reduce()`, except a minor difference that does not really need to concern you in terms of usage of this lib), with some fancy methods around it...

Rest is just ideology/principles.

Really, if I were to make side by side comparison, it'd look basically identical, except that redux would not work out of the box.

## redux

```
function counter(state = 0, action) {
  switch (action.type) {
  case 'INCREMENT':
    return state + 1
  case 'DECREMENT':
    return state - 1
  default:
    return state
  }
}
```

```
createStore(counter)
```

```
store.dispatch({ type: INCREMENT });
```

## store

```
function counter(state = 0, action) {
  switch (action.type) {
  case 'INCREMENT':
    return state + 1
  case 'DECREMENT':
    return state - 1
  default:
    return state
  }
}
```

```
provideStore(counter)
```

```
store.dispatch({ type: INCREMENT }); 
```

---

> so it doesn't seem to be common knowledge that RxJS can already do almost everything Redux does...

http://redux.js.org/docs/introduction/PriorArt.html#rx

![image](https://cloud.githubusercontent.com/assets/1303561/12327710/47434a74-bad8-11e5-96df-a67e518d1f6a.png)

I'd be better to learn something about rxjs/reactive programming, rather than look at comparisons, because it's literally the same except lesser pain in the ass when you are already working with observables(as store is just one big observable).

**Comment by fifafu** [comment]
Thanks!
Unfortunately often people don't have time to learn new concepts when they have to decide which technology to use, thus looking at comparisons often helps as a first step. The answer you just posted already helped me tremendously!

I think Redux has gained so much momentum during the last few months that many people will be looking on how to use it with AngularJS 2, thus I think it's important to communicate that you do not need Redux at all.  Knowing that Redux is (almost) a two liner with RxJS is quite cool.

**Comment by JamesHenry** [comment]
I think one important thing that comes under this, but which has not been mentioned, is the amount of "extras" that have been built with/for Redux. A user of ng2 + redux could benefit from these immediately, whereas this project is only an equivalent to the capabilities of the redux library itself.

The redux dev-tools are particularly useful.

See: http://rackt.org/redux/docs/introduction/Ecosystem.html

Don't get me wrong, I know this effort has literally just started, so there is no expectation that there would be a rich ecosystem around it, but I still think it forms part of comparison between the two.

---

![unspecified](https://cloud.githubusercontent.com/assets/900523/12350649/392f55ac-bb70-11e5-9b25-7fe545dd67be.png)

**Comment by robwormald** [comment]
So i'm a big fan of Redux, and obviously this lib is highly inspired by it. That said, for Angular2 apps, there are some specific advantages, and a whole set of other advantages that come with using Rx for this sort of thing.

The first (and by far the most important, imho) and the reason this library exists in the first place is change detection. Assuming you maintain all your state in `Store`, and you use the async pipe to wire up to the view:

``` typescript
constructor(store:Store){
  this.todos = store.select('todos');
}
```

``` html
<ul>
  <li *ngFor="#todo of todos | async">{{todo.text}}</li>
</ul>
```

You can actually effectively disable change detection in your Angular2 app for any component where you handle things this way (!) 

``` typescript
import {ChangeDetectionStrategy} from 'angular2/core'

@Component({ 
  selector: 'todos-list',
  template: ....,
  changeDetection: ChangeDetectionStrategy.OnPush
})
```

Which can lead to massive performance boosts in larger applications, even over Redux's immutability guarantees.

The other ergonomic benefit that goes along with the above is that the `.subscribe()` method actually delivers you the new state, rather than having to call getState() as you do in redux. This is minor, but its how Rx works by default so its a nice little improvement.

Since it's based on RxJS, a lot of the stuff listed in @JamesHenry's list there sort of comes for free as well, or doesn't really require any special handling. A lot of Redux middleware is handled by RxJS operators like `.map()`, `.filter()`, `.mergeMap()`, etc. Reselect is `.distinctUntilChanged()` and/or `.combineLatest()`, `.withLatestFrom()` or `.merge()` . Undo/Redo can be handled with `ReplaySubject()`. Batched actions can be handled with Rx schedulers. 

My aim here is not to replace or "beat" Redux in any way - indeed, I probably watched @gaearon's  egghead series a dozen times while working through the initial implementation of this library. It's a brilliant library and this is simply a slightly different interpretation of the same fundamentally excellent idea.

Devtools though, are awesome. They are definitely on the roadmap.

**Comment by JamesHenry** [comment]
Thanks a lot for those examples @robwormald, that really helps clarify the project's raison d'être and potential future direction.

I will definitely keep it in mind as we migrate our large ng1 app over to angular 2 in the near future.

PS I'll second how great @gaearon's egghead course was :) thanks a lot for redux, Dan!

**Comment by NathanWalker** [comment]
That's a hella' awesome additive explanation @robwormald ...huge thanks for that!!! +:100:

**Comment by bertrandg** [comment]
Really interesting discussion here, thanks for this promising lib @robwormald!
I've just seen you have a conf named 'Reactive Angular 2' at NG-NL (http://ng-nl.org/). 
Are you gonna talk about ngrx ?

**Comment by fifafu** [comment]
@robwormald that was exactly what I was looking for. Thank you very much for taking your time to post that explanation!

Devtools would be awesome. I'm definitely looking forward to use this library very soon.

**Comment by robwormald** [comment]
@bertrandg yeah, i think so. i'll be talking about "practical reactive ng2" and this lib will probably feature as part of that talk.

**Comment by gaearon** [comment]
I would like to note that you don't have to use Redux to benefit from Redux ecosystem (DevTools, middleware, etc). Just write something like `toReduxStore(ngrxStore)` and use it. DevTools and other stuff doesn't care whether it's “really” a Redux store as long as it implements the same (quite small) contract.

**Comment by JamesHenry** [comment]
That is awesome, thanks for pointing that out @gaearon - _really_ glad I brought it up now :smile: 

As an aside, it is just so great to see such open inspiration and communication between different JS projects. Most people seems to love a good battle between "rival frameworks", but this is cross-project OSS idea sharing at its finest! Bravo.

**Comment by robwormald** [comment]
Just in case anybody is itching to implement devtools, here's a super rudimentary implementation to get you started... :smile: 

http://plnkr.co/edit/3rUbz8HXeMsRnuSvlMgL?p=preview

**Comment by robwormald** [comment]
do need to have a bit of a think about how to implement setState, as the semantics are a bit different in a `.scan(reducer, initialState)` scenario.

**Comment by gaearon** [comment]
What do you mean by implementing `setState`? Neither Redux nor ngrx Store have it AFAIK.

**Comment by robwormald** [comment]
`setState` as a generic concept for undo/redo (hopefully without having to add a specific `case` to each reducer:

``` typescript
//dispatcher is an Rx subject:
const dispatcher = new Subject();

const state$ = dispatcher.scan(reducer, initialState);

state$.subscribe(state => { ...});

```

given that (currently) the only way to directly affect state is to .next() an action through the dispatcher, it will require a bit of reorganizing to wholesale reset a state (i would imagine i'd just wrap up the reducers to manage this, just hadn't given it a whole lot of thought yet. ideas?

**Comment by gaearon** [comment]
Have you looked at how Redux DevTools solves this? It wraps reducer with a "meta" reducer that has its own "meta" actions such as "toggle action".

**Comment by gaearon** [comment]
As I said before you don't have to implement this from scratch. You can use Redux DevTools pretty much as is (there's some non trivial code there that would be a shame to have to re-implement). You just need to convert your store to a Redux Store. Alternatively I can look into exposing something more generic from Redux DevTools to make interop easier.

**Comment by born2net** [comment]
My biggest debate if to use the official Redux release or the Rxjs based @ngrx/store is that the Eco system around @ngrx/store is still small and it doesn’t have all the DevTools and cool middlewares… but I do like the core Rxjs of it… so I am not sure which path I should take,... Thoughts? and corrrect me if I am wrong but you can still use the async pipe with standard Redux release, right? (or will it feed only from Observables?)

**Comment by fxck** [comment]
As @gaearon said, it's not really hard to use devtools with this library. Also which cool middleware do you need?

And no, async pipe won't work, you'd first need to write a wrapper(https://github.com/ngrx/store/issues/16#issuecomment-171665825) around redux. But honestly, all respect to Dan, but I would pick store over redux in angular2 every single time.

**Comment by born2net** [comment]
there are some cool middlewares... (like pouchDB) but yes right now I am not sure yet if I will need any...

**Comment by born2net** [comment]
I did have one comment, as noted above by the dev "The first (and by far the most important, imho) and the reason this library exists in the first place is change detection....." but I am not sure this is a point for comparison as you can STILL use onPush detection with Redux... for example: https://github.com/InfomediaLtd/angular2-redux-example/blob/master/app/views/film/film-view.ts

I did dig into his source and found that he did do a wrapper for Rxjs: https://github.com/InfomediaLtd/angular2-redux/blob/master/src/app-store.ts  but I still feel you can use onPush strategy even without that wrapper, since the data updates always come from the outside (i.e.: the parent who connects to the store) (just trying to learn ... so appreciate your replies fxck :)

**Comment by gsans** [comment]
Anybody knows of any Redux Dev Tools examples without depending on React
(using Angular 2 or not)? It would appear as they are coupled together. Eg:
https://github.com/wbuchwalter/ng2-redux depends on react, react-redux and
redux-devtools.

**Comment by gaearon** [comment]
The core of DevTools is completely decoupled from React:
https://github.com/gaearon/redux-devtools/blob/master/src/instrument.js

The React API is a tiny wrapper above it and it's entirely possible to build an equivalent one in Angular:
https://github.com/gaearon/redux-devtools/blob/master/src/createDevTools.js

Finally, of course the _monitors_ (the UI) for DevTools are written in React, including the default one, but again, totally possible to build with Angular if you want to.

**Comment by gsans** [comment]
This looks like an excellent opportunity to port some UI monitors to
Angular then. I'll look into it. Thanks Dan.

**Comment by btroncone** [comment]
I am more than happy to help with documentation for this project once the API becomes stable(ish). Just let me know where to start! :)

**Comment by robwormald** [comment]
undo/redo with @gaearon's example reducer decorator pattern http://plnkr.co/edit/UnU1wnFcausVFfEP2RGD?p=preview

**Comment by MikeRyanDev** [comment]
I've thrown together an experimental branch that has both Redux's devtools and a mostly complete Angular 2 implementation of the log monitor: https://github.com/mikeryan52/store/tree/feat/dev-tools

There are a number of breaking changes I had to make to the lib to get it working:
- Instead of providing a key/value map of reducers, you must provide a complete reducer function. This could be easily worked around if @ngrx/store exported a `combineReducers` function like Redux does
- I've loosened the Action interface 
- Temporarily removed the ability to swap out the reducer function, though it should be extremely easy to add back in
- You would no longer want to subscribe to the Store class directly, instead relying completely on `select()`
- You would no longer want to use the `Dispatch` class directly, instead relying completely on `Store.dispatch()`

The way the instrumentation works is that it has its own state and computes the application's state itself. All actions dispatched in application land have to be lifted, and all state access methods need to be lifted as well. In the experimental branch I do the lifting by subclassing `Store`, though in retrospect there are probably some better ways to do this.

While the changes sound drastic, they allow much better interop with the Redux ecosystem. If you take a look at `/lib/instrumentation.ts`, you'll see it is almost identitical to `redux-devtools/src/instrument.js`. Only changes I had to make were a few extra exports and some light typing.

**Comment by gaearon** [comment]
It would be pretty awesome to not have to duplicate the instrumentation core. If there is shared code we can extract that both projects could use we would be happy to do that.

**Comment by robwormald** [comment]
@MikeRyan52 thanks for trying this out. I'm hesitant on a couple of those breaking changes, mostly the one where you're unable to subscribe to the store directly - that's a key component of the API for me (that is, the state is an Observable itself.)

Under the hood each reducer is wrapped in an Observable and they are zipped together, which is why there isn't a public combineReducers function. I don't recall exactly why I made that design decision so I'm open to reworking that to work against a single rootreducer, which would probably make this a little easier. I'll have a look at this more closely this afternoon. 

Note that BehaviorSubjects (of which Store is a subclass) do have a .value property to get the current state sync - it's not super reactive but is probably useful for this case. 

@gaearon that would be rad, I'll open up another issue to track devtools work.

**Comment by gaearon** [comment]
I haven’t looked closely at either version of the API but I think the core idea that makes DevTools possible is that the store (or some part of it) can be represented as `(Reducer<State, Action>, Observable<Action>) => Observable<State>`. This should be enough for the “lifting” business.

**Comment by MikeRyanDev** [comment]
@robwormald Agreed, my initial take on lifting the store had some serious flaws. I've come up with a much better solution: https://github.com/MikeRyan52/store/blob/feat/dev-tools/src/devtools.ts#L30

Now the store is lifted and you can still subscribe to it as an observable.

**Comment by laurelnaiad** [comment]
I've been planning to build an ng2/redux app, and to use redux-rx's [observableFromStore](https://github.com/acdlite/redux-rx#observablefromstorestore) feature to bridge the short gap between redux's store and angular's penchant for Rx goodness.... 

Aside from the redux-rx approach maintaining an actual redux store instead of this store, what else might I expect to be different in these approaches?

**Comment by robwormald** [comment]
@laurelnaiad conceptually they are very similar. in an observableFromStore situation, downstream of the store there's not going to be a lot of difference. But - rx-redux, as far as I'm aware, uses RxJS 4.0, while NG2 uses Rx5. There may be a few issues with that (and you'd be bringing in two version of Rx + Redux itself)

**Comment by laurelnaiad** [comment]
Right -- well let's assume that I would translate all 5 lines of observableFromStore to work with RxJS5 :)

.... I'm trying to understand why creating an entirely different store is helpful (with the attendant need for efforts to compatible-ize it with devtools and middleware, etc.) vs. just dangling observable from the redux store... what is gained by creating the store here "from scratch"? I'm not asking to to challenge the viability, I'm asking out of actual (or what I at least perceive to be my own) naïveté.

**Comment by robwormald** [comment]
- no external dependencies
- most of the redux devtools ecosystem is based on react components. 
- store itself implements Observer - `actions$.subscribe(store)`
- dependency injection friendliness
- typescript compatibility
- because we can? 

I don't mean to be short, but try them out for yourself and see which you prefer. I don't buy the arguments that we should all be focused on a blessed solution. I hear it all the time, and I think it does a disservice to people who are exploring new solutions. Don't feel the need to justify it any further than that.

**Comment by laurelnaiad** [comment]
Heck, you're allowed to be as short or long as you want! I was just trying to understand how you see the difference now and in your vision for what's next. Thank you for your thoughts and for sharing this. I've just finished battling my way through all of those bullets in straight redux/ng, so it's an interesting time for me to be considering whether or not staying in redux proper makes sense. I guess it should be pretty easy to swap one for the other without upsetting my cohorts' applecarts, too much.

**Comment by laurelnaiad** [comment]
(after a little more than a week with ngrx/store, I'm very glad I made the switch. I guess I got observable religion. ) Thanks, @robwormald. :)

**Comment by robwormald** [comment]
yeah, gotta watch out for that, pretty soon you'll be at conferences raving about streams. glad it's working out for you.

**Comment by jimitndiaye** [comment]
@robwormald on a slightly related note, will you be keeping the store sample repo up to date with changes in ngrx/store? Just tried cloning and running it but ran into a bunch of errors, possibly due to npm pulling incompatible versions of dependencies.

**Comment by fxck** [comment]
Rob didn't contribute to the example app. @meenie and others did, but we've all been quite busy. I might try and update it over the weekend.

**Comment by btroncone** [comment]
@jimitndiaye I have aggregated additional examples [here](https://github.com/btroncone/ngrx-examples) as well. Hope that helps!

**Comment by jimitndiaye** [comment]
thanks @btroncone. That did help :)

**Comment by btroncone** [comment]
Awesome, glad to help! :)

**Comment by mpetkov** [comment]
Hey all, I was in the process of starting to implement Redux into my Angular2 app until I stumbled on this library.  So I read the entire thread and there was a lot of back and forth on which to use.  So now since some time has passed, do you see more people using this library vs redux to manager their app states in Angular 2?  Also, is this library used much outside of angular?  The reason why I was leaning towards Redux was because it was used by many different JS frameworks.

**Comment by alehatsman** [comment]
@mpetkov trying to find the same answers

**Comment by CharGrnmn** [comment]
@Atsman @mpetkov In my humble opinion, I really do think that you should use ngrx/store, especially if you plan on using Angular2, or working within a reactive environment. Your question(s), actually inspired me to write the following https://medium.com/@charlie_gee/redux-vs-rxjs-ngrx-store-db6066058719#.jpe9fbto5

**Comment by playground** [comment]
I'm exploring ngrx and am wondering if there is an ngrx version of https://github.com/ng-book/angular2-redux-chat out there.

**Comment by shprink** [comment]
After reading this thread I decided to write a blog post about it [From Redux to ngrx/store](https://julienrenaux.fr/2017/02/16/from-redux-to-angular-ngrxstore/)

**Comment by emcpadden** [comment]
@shprink great blog post ... thanks!
