### ISSUE TITLE
[question/proposal] Difference between this project and ng2-redux

### ISSUE THREAD

**Issue by akomm** [ngrx/store#169]
Hello,

I'v found redux+ng2-redux (binding) and this project. Now I'v tried to see the difference to decide which project to use.

This project is not based on the redux project, compared to ng2-redux, which kind-of wraps redux with observables and provides some decorators. Both projects use rxjs and same concepts though. As the readme states, it is inspired by redux. 

Beside that, If someone is checking this two projects (ngrx/store ng2-redux) out it is not initially clear, what this project wants to do different or does different by not using redux. Not using something, that already exist usually has reasons. 

I can imagine that other people like me would appreciate some small note in readme, beside the one that this project is inspired by redux, why one might want to use this and not ng2-redux. #

**Comment by MikeRyanDev** [comment]
There are subtle nuances between @ngrx/store and ng2-redux that are not particularly interesting but I'll try to explain them anyway:

The process for creating a Redux store with middleware using the actual [Redux library](https://github.com/reactjs/redux) maps poorly to Angular 2 DI providers. Passing dependencies to middleware is a hard problem and getting the [actual Redux devtools](https://github.com/gaearon/redux-devtools) to play nicely with change detection can be tricky. @ngrx/store and ng2-redux are different reactions to this problem set.

@ngrx/store has gone the route of re-implementing the Redux pattern in an Angular 2 and Rx friendly way. Configuring the Store is done with providers, the API surface area is small, our [side effect library](https://github.com/ngrx/effects) (which fills the role of most Redux middleware you would want) works great with DI, and our devtools are universal components ready to be rendered in a webworker thread or on the server. In short, because we are so focused on making @ngrx/store work well with Angular 2 I think we provide a great out-of-the-box experience for Angular 2 developers. In doing so, however, we sacrifice compatibility with Redux's vast ecosystem and have had to re-implement a lot of the infrastructure ourselves. 

ng2-redux on the other hand uses the real Redux library under the hood and is thus compatible with much of the Redux ecosystem. This means they aren't re-implementing Redux infrastructure and have access to some really awesome tooling. The cost, however, is that it is (and this is my opinion here) a little clunky. Configuring the store in the root app component constructor is novel and not in a particularly pleasant way, though it does solve the problems listed above.

A few months ago, the libraries were a lot more different. Both teams have worked hard to narrow the gap and I predict given enough time it will be difficult to distinguish between the two. If you are having difficulty picking, honestly the best thing to do is to build something using both implementations. It should give you a clearer idea of each's strengths and weaknesses.

As the above explanation is long and likely to change, I'm going to go ahead and close this issue and not make additions to the README. It isn't an "us vs them" situation and I'd like to try and keep it that way. 😄

**Comment by akomm** [comment]
Thank you for taking the time to explain! :+1:

**Comment by DeeM297** [comment]
Thank you for the link. That's exactly the problem I'm facing: 

> The process for creating a Redux store with middleware using the actual Redux library maps poorly to Angular 2 DI providers. 

The project was working with rc4 and now in angular 2.0.0 and AoT, I'm having a hard time with it. I've tried to applied what's written in this post: [Making your Angular 2 library statically analyzable for AoT](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5) 

I'm following AoT best practise by changing _const lambda_ into _export function_ but then getting stuck in using the store.
```
// const appStore = createStore(
//   rootReducer,
//   applyMiddleware(ReduxThunk)
// );

export function appStore(): any {
  return createStore(
            rootReducer,
            applyMiddleware(ReduxThunk)
          );
};
```

One idea I'm exploring is to take the _createStore()_ out of _app.module.ts_ and do it in an independent provider. 

And just found this project which took the same route: [Angular/Redux Complex UI Example](https://github.com/ng-cookbook/angular2-redux-complex-ui/blob/master/src/app/app-bootstrap.ts). 
I'm going to try and see what happens.

**Comment by Josh68** [comment]
I personally think putting something like this in the docs would not make for an "us vs them" situation and, for the record, I asked the Rangle.io team if they might do the same from their POV. Seems it would be helpful for making choices. Thanks for your work.
