### ISSUE TITLE
Any issues / ok to use with Immutable.js?

### ISSUE THREAD

**Issue by born2net** [ngrx/store#23]
so I decided to go ahead and adopt this lib for our next large project.
Do you see any issues or thinks to watch for is we will use this lib with Immutable.js?

regards

Sean

FYI this lib is mentioned here:
http://victorsavkin.com/post/137821436516/managing-state-in-angular-2-applications

NICE!!!

**Comment by mikekidder** [comment]
Immutable.js is used in their own initial sample -- https://github.com/ngrx/angular2-store-example

And getting some immediate endorsements - https://twitter.com/eggheadio/status/688023660431556609

**Comment by born2net** [comment]
great tx, will study the code...

**Comment by simonh1000** [comment]
Is this still valid? ngrx seems to handle the top level of splitting out the store, passing it to the reducer and recombining behind the scenes. I presume it assumes normal JS objects, so I don't see how immutable.js can be used at the top level

**Comment by born2net** [comment]
fyi I ended up going with pure immutable and redux with typed models and LOVING it.

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by laurelnaiad** [comment]
Immutable.js is one of a few libraries that will help you freeze your state objects, but if that's all you want, there are lighter weight alternatives.

It shines b/c it has efficient implementations (especially when using sequences) of lots of standard frp functions, like rxjs without the time dimension.

**Comment by kylecordes** [comment]
When I last looked at this there appeared to be a somewhat ugly trade-off, by going to an immutable data structure library you are no longer using typescript data structures and the straightforward way that makes typescript types work. You end up accessing the data structures by calling functions passing a parameter of a field names and so on, and that puts (for example) the names and types of fields and an object outside of where the typescript type system can see it.

From the discussion here though, I'm hopeful that I overlooked something, and there is a way to get robust typescript type support simultaneously with immutable ("persistent") data structures?

**Comment by born2net** [comment]
actually I am a BIG fan of TypeScript.
You should checkout my setup, I used base class typed Model which all my models which get injected into my Redux get intelisence goodness.
It's an amazing setup that gives me flexiblity, redux tools including redux chrome extension and much more and all coupled with immutability.

base model:
https://github.com/born2net/studioDashboard/blob/master/src/models/StoreModel.ts

subclass of model example with added custom methods:
https://github.com/born2net/studioDashboard/blob/master/src/adnet/AdnetContentModel.ts

a fully typed reducer example:
https://github.com/born2net/studioDashboard/blob/master/src/adnet/AdnetReducer.ts

and throughout the application I get typed awesomeness:
https://github.com/born2net/studioDashboard/blob/master/src/comps/app1/adnet/rates/AdnetConfigRates.ts

see how I subscribe to the model with typed goodness including immutability typed to the model as in List<AdnetPackageModel> ( immutability + ts )

its a perfect setup and I really need to make video so I can better brag about it :)

**Comment by awerlang** [comment]
I agree with @kylecordes. At first you'd like to try it out (ImmutableJS), because it's a new thing, then you discover it's not plain objects you're dealing with. Its just a hassle. Another API you'll never learn enough.

While maintaining immutability is not required for reducers, most people do this way. With ES2015/TS, It's very easy to create new objects/arrays from another, and if you want to enforce immutability at development use the `store-freeze` meta-reducer. For production you'll probably leave it out, then you don't have to incur performance costs.

Another good tip is keeping your store tree as shallow as possible, as it is better for maintenance. There are also tools that help with plain objects like `updeep`, but give a change to Array methods (`filter`, `concat`, etc) and `Object.assign`.

ImmutableJS was probably a good choice pre-ES5, but we're in 2016 and the platform evolved a lot.

**Comment by born2net** [comment]
in my opinion, storing plain objects on a store is a BAD idea...
I can't tell you how many times my ass was saved because I was dealing with a typed model.
@awerlang please checkout my code above, you really get the best of all worlds
- typed models
- immutability safety
- immutability processors (filter, find etc)
- store chrome extension
- onPush ng2 speeds
  and more...

check it out, you will be impressed!

regards

Sean

**Comment by awerlang** [comment]
@born2net 

> a fully typed reducer example:
> https://github.com/born2net/studioDashboard/blob/master/src/adnet/AdnetReducer.ts

May I ask you what _fully typed_ means to you? I see strings everywhere, how much automated help would you get if you were to rename the `rates` or `targets` field?

> in my opinion, storing plain objects on a store is a BAD idea...

Huh, I find the opposite. Im my own experience, plain objects are all I need.

> typed models

Plain objects or even classes with plain properties can

immutability safety
immutability processors (filter, find etc)
store chrome extension
onPush ng2 speeds and more...

**Comment by awerlang** [comment]
@born2net 

> a fully typed reducer example:
> https://github.com/born2net/studioDashboard/blob/master/src/adnet/AdnetReducer.ts

May I ask you what _fully typed_ means to you? I see strings everywhere, how much automated help would you get if you were to rename the `rates` or `targets` field?

> in my opinion, storing plain objects on a store is a BAD idea...

Huh, I find the opposite. Im my own experience, plain objects are all I need. They're simple to handle, and I don't have to use strings to access anything. All know the type of every property.

> typed models

I use plain objects or even classes with plain properties. Much less boilerplate.

> immutability safety
> immutability processors (filter, find etc)

I get these with `Object.assign` and Array methods. And `Object.freeze` on development only.

> store chrome extension

I don't bother with these.

> onPush ng2 speeds and more...

Do you have benchmarks to prove ImmutableJS perform better than plain objects? I would like to see an NgFor over an array with nested components.

**Comment by awerlang** [comment]
> check it out, you will be impressed!

I'll certainly take a look. I'm curious about using redux directly. But overall you're following a path I won't go (ImmutableJS, etc)

**Comment by born2net** [comment]
I get 100% typed help, if I get back a Model, it has to be of proper type or I will get an error, no string are used, unless I call a method of the model. as far as speed, I am sure its just as fast rx no nothing on that front, I meant you just get onPush (which you would with rx as well) on angular 2.

**Comment by dsebastien** [comment]
At work we use TS classes for the domain model, including the things we put in the store. We care about immutability so we've chosen to use seamless-immutable; it is (as the name indicates) quite seamless and much nicer to work with than having to learn all the API of Immutable.JS: https://github.com/rtfeldman/seamless-immutable. We've contributed some typings so the API is easy to use with TypeScript.

What I like about having a library for immutability is the fact that it makes it clear you are dealing with immutable objects. 

The alternative that we are investigating now is dropping seamless immutable (at least in the context of Redux) to maybe switch to Object.assign and the spread operator in the reducers, combined with https://github.com/codewareio/ngrx-store-freeze in order to protect us from mutations in the reducers but also from the outside when deep references are kept (see https://github.com/codewareio/ngrx-store-freeze/pull/1).

I'm actually more in favour of seamless-immutable and the "in your face" aspect of the immutability, but there are pros and cons to consider :)

**Comment by simonh1000** [comment]
My original question was that - using angular-cli file strucutres - I have the following in app.module.ts.

```
    StoreModule.provideStore({
      restos: restosReducer,
      filters : filtersReducer,
      selectedResto: selectedReducer,
      mapReady: mapReducer
    }, {
      restos: [],
      filters: Immutable.Map(initFilters),
      selectedResto: [],
      mapReady: false
    }),
```

It looks as though ngrx itself handles the passing of the elements of my state to the individual reducers, and it's not clear whether it does that in an mutable or immutable manner. 

I tried Immutable as an experiment and think i will go back to Object.assign for this project, as it is a pretty simple one otherwise

**Comment by karlhaas** [comment]
We first started in our project with using Immutable.js Record for our model classes. Soon we needed a base class for our model classes and came to the same approach as @born2net. But since then, I was often annoyed by the additional API of Immutable.js and difficulty when working with nested objects. I want to use Immutable.js just in my model classes and don't care about the additional API in my components, services. This quickly leads to a lot of conversion operations between immutable inner representation of the private Map and the non-immutable, or again wrapped version, of the provided values by get operations...

We are thinking about switching to a simpler approach using some kind of store freeze in development mode and TypeScript readonly for the model properties.@dsebastien thx, didn't know seamless-immutable.

**Comment by kylecordes** [comment]
I haven't kept up with the conversation fully, but when I was asking about full typing support I mean the same thing as @awerlang said; I am trying to avoid code like what I saw in the linked reducer example, I'm hoping to never write something like this:

```
return state.setIn(['customers'], action.customers);
```

Because the word customers in that string is sitting there outside the view of the type system, outside the view of the re-factoring tools in my IDE, Etc.

I'm not sure if it was possible to achieve this; I suspect it is not possible to achieve it with typescript (which is amazing, it just doesn't stretch in direction that would make it possible to put full typing support around libraries like this).

"seamless-immutable" does not achieve it, it is not seamless as far as types are concerned, because it still uses set("string", ...).

Here's what I have settled on as "good enough" for most work:
- Just use ordinary typescript objects the full type support "everywhere".
- Deep clone as needed, to ensure none of my code accidentally relies on state representation objects being mutated in place.
- Occasionally back down from deep cloning or just skip it entirely, once I'm sure the program is working correctly; if necessary I can even put in a switch that turns it on and off if I ever spot a bug that could possibly be connected to it and need to briefly go back to aggressive preemptory deep cloning.

This is not perfect, but it keeps extensive type support and takes very little work. I value types a lot and I value immutability a lot, at the moment for most of my work types seem to win slightly in the trade-off that has to be made here.

**Comment by KwintenP** [comment]
@kylecordes I completely agree. Plain typescript object provides you with better typing support throughout your entire application. 
The only downside, as you mention, is references from objects in your store being updated outside of your store. To avoid this problem, you can use a deep-freeze meta reducer to assure you're not doing this by accident.
In production, you could just remove this meta-reducer.
F.e.: https://github.com/codewareio/ngrx-store-freeze/issues

**Comment by kylecordes** [comment]
@KwintenP Excellent - I will start using that instead of the ad-hoc was I was achieving the same thing.

**Comment by rupeshtiwari** [comment]
I have tree view deep nested data in my state therefore it is not straight forward to update using object.assign or spread operator. Therefore I am going to use immutable.js

**Comment by littleStudent** [comment]
If anyone runs into this question, there is also another alternative.
If you only look for a way to do immutable updates in nested state i recommend something like http://ramdajs.com.
immutable.js offers much more but also requires more setup and adds more complexity.

**Comment by rupeshtiwari** [comment]
@littleStudent thanks for pointing me to Ramda.  I saw first time Ramda in action on Ng-conf reactive forms with selector video.  I am going to research Ramda now to figure out how to update tree view and other plain objects.  Do we have any sample app where ngrx store with combined reducers is used with Ramda ? I agree immutable.js has many ceremonies also will have to figure out combining state in reducer also in smart component i have to convert it to plain object and pass it to dump.  Many conversions. Also I don't like the hardcoding property names while updating object via immutable.js like  @kylecordes pointed out.

**Comment by rupeshtiwari** [comment]
Hi @littleStudent , I played little bit with Ramda and able to update nested property without changing my datatype.
Immutable.js was changing data type so lot of conversions were involved. However, I loved the way Ramda works. I am very happy with Ramda. Also I created plunker app to demonstrate one sample to update nested tree view structure using RAMDA.
https://plnkr.co/edit/v2InD0?p=preview
https://embed.plnkr.co/v2InD0/
