### ISSUE TITLE
Rxjs 5 is deprecating "Select" in favor of "Map"

### ISSUE THREAD

**Issue by wiredprogrammer** [ngrx/store#237]
Forgive me if you've discussed this somewhere else but in updating everything for the final release of Angular 2 I noticed that RXJS 5 no longer has support for "select".

I know "select" has sort of become a iconic operator for ngrx/store but I'm wondering what the discussion has been around maybe shifting to "map" to be more inline with the RXJS 5 operator implementations.

https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md

Thanks!

**Comment by laurelnaiad** [comment]
The `.select` function on store was never equivalent to the `.select` function from Rxjs. (it applies a distinctUntilChanged() after the map, see https://github.com/ngrx/core/blob/master/src/operator/select.ts) I think it's good the rxjs is cleaning up the terms, but I'm not sure if this change ought to have an influence on ngrx .select (which lives in ngrx/core), as if anything it frees up the word to take on a meaning other than map in the ~~minds of an rxjs person~~ minds of rxjs people (whoops -- no, rxjs people do not all have multiple personalities 😄 ). 

EDIT: corrected link. Tx, @denkomanceski  .

**Comment by denkomanceski** [comment]
The dot at the end of  the link makes it a 404 link 💃

**Comment by SethDavenport** [comment]
`select` in the Redux headspace has its own meaning, influenced by libraries like reselect. A selector in Redux is a pure function that transforms store state to what the UI needs on the way out of the store. NgRx's `.select` performs an analogous role, albeit as a distinctUntilChanged stream instead of a memoized function.

So personally I agree with @laurelnaiad
