### ISSUE TITLE
Drop .select() method?

### ISSUE THREAD

**Issue by robwormald** [ngrx/store#34]
Rationale:
- `.select()` exists in Rx4, and ours uses a different interface - may be confusing / might get replaced if somebody implements select for Rx5.
- our `select()` method is basically a combination of two operators - you can use it like `.map(project:fn)` with a selector function, or use it like `pluck(key:string)` - pluck didn't exist when I implemented store originally but it does now. 
- our select does call `distinctUntilChanged()` internally, and i'm wondering if that's a bad idea.

Would be deprecated rather than immediately removed, but I think it should be done sooner than later. 

Discuss?

**Comment by cschiavolini** [comment]
my 2 cents
from user perspective the `.select()` operator is very powerful combined with async pipe (that I suppose it is the reason why the operator exists in the first place)
I could surely use `.map` and not much would change, apart from having to eventually apply `distinctUntilChanged()` as well.

I cannot see a case where `distinctUntilChanged()` might be a bad idea, unless one needs to apply a particular comparator, instead of relying on object equality. 
Considering all of the above, the operator is a useful short cut. 

About the name of the operator itself, we already know that naming is one of the 2 most complicated things in software development and I see how the conflict with Rx can cause trouble. 
Being not good at renaming stuff, my simple proposal could be `stateSelector` or something similar that might imply the need to get a portion of the whole state

**Comment by fxck** [comment]
.tree(name)

.key(name)

.pick(name)

**Comment by artaommahe** [comment]
as @cschiavolini said `distinctUntilChanged()` is very usefull.. it's good idea to rename select to `stateSelector`. And there is one issue  - it can be very usefull to use `pluck()` instead of `map()` in select, because of nested selectors, but `pluck()` cannot be used with function :(

**Comment by cjavdev** [comment]
I like the convenience, but agree that the name might cause confusion

**Comment by robwormald** [comment]
i'm gonna leave it in for now
