### ISSUE TITLE
 'payload' does not exist on type 'Actions'

### ISSUE THREAD

**Issue by yaronmil** [ngrx/store#350]
```
export function reducer(state = initialState, action: processesActions.Actions): State {
  switch (action.type) {
    case processesActions.PROCESSES_LOADES:
      action.payload
```

>  error 'payload' does not exist on type 'Actions'

**Comment by diicar** [comment]
@yaronmil  you needs to do something like this : (< YourAction > action).payload

**Comment by yaronmil** [comment]
@diicar thank u, i was casting my action to ngrx Action and it work.

the demo app is using the `payload `property with no casting .
, i wonder how can it be ?

**Comment by diicar** [comment]
@yaronmil Are u exporting your the action class in your action file?
**export type Action = XyzAction | .... ;**

**Comment by yaronmil** [comment]
@diicar yes i do like this :
```
export type Actions
  = classA| classB| classC
```

**Comment by diicar** [comment]
I think, from the moment we have different type of payload, we have to tell **tsc** which kind of object that we are dealing because it's cannot be inferred properly in our case.

**Comment by karolmie1** [comment]
@yaronmil  You know, it's best if you provide plunkr or link to your repository. That way you'll get quicker and better answers with no guesswork.

**Comment by yaronmil** [comment]
@karolmie1 i dont know how to do that

**Comment by yaronmil** [comment]
@diicar payload is declared on interface 

> Action

 and is of type `payload?: any;`

**Comment by karolmie1** [comment]
Well, you go to your repository, you copy the link and post it here :)

**Comment by yaronmil** [comment]
@karolmie1 , do you meenmean  to this :

 

the error was at line 34 , so i cast it

**Comment by diicar** [comment]
Have you tried this ? 
```
case processesActions.PROCESS_CREATED:
      const newProcess=(<processesActions.CreateAction> action).payload ;
      const processesList=[...state.processesList,...newProcess]
      return Object.assign({},state,{processesList});
```
The **Action** you used is from **@ngrx/store**

**Comment by yaronmil** [comment]
@diicar  this works , thank u

**Comment by gregbown** [comment]
Typescript 2.2.1, Angular 4.0.0-rc.3 I was unable to have actions with different type payloads or an action without a payload because it would throw a compile error in the reducer that payload didn't exist on an action that clearly had a payload. Somehow it would confuse the action type in the reducer giving me an error at the CompleteAction that the type payload does not exist on the InitAction? 

Syntactically my code is identical to the ngrx example app, book actions and book reducers where one action has a payload string and another has a payload Book, so, I was quite baffled, and found no reason why my compiler was complaining other than maybe the later version 2.2.1?

Thank you @diicar your fix worked
