### ISSUE TITLE
Recommendation of ngrx in enterprise level applications

### ISSUE THREAD

**Issue by nitink85** [ngrx/store#372]
@robwormald @MikeRyan52 I need a recommendation, till what extend we suppose to use ngrx in enterprise level applications. 

My concern, If I store all user actions with there request/response as a payload in store, so that it could help me in replaying the states when needed for troubleshooting any issue. It will grow my states gradually with time. As I am thinking it will consume more virtual memory, and consumption will grow with time.

Example, If I have an application of 100 pages with at least 5 actions, and on each action we're making an API call. Then we would have 500 actions and there generated states in store. Does not matter we moving from one page to another, there actions and states would still exist in store. Would this existence consume browser(which consumes virtual memory) and cause application crash, leakage or any unexpected behavior?

**Comment by karptonite** [comment]
I'm not 100% certain, but I don't believe that all actions are saved, unless you are using store-devtools in production--only the current store. Someone else who knows better should comment on this, and also what happens if you use store-devtools with instrumentOnlyWithExtension--I seem to remember reading somewhere that that isn't a problem for browsers that don't have redux devtools installed. Moreover, you can set maxAge on store-devtools, so that it only stores a certain number of actions before purging.

The store could still grow without bounds if you add things to it without clearing items as you jump from page to page, though. The fix for that could be as simple as adding a ClearItemsAction of some sort that triggers when you jump from page to page.

**Comment by robwormald** [comment]
Actions are not retained, they're garbage collected (unless you do something explicitly to hold onto them, which is generally a bad idea outside of devtools.
