### ISSUE TITLE
What are some benefits of using ngrx vs relying on services for data manipulation?

### ISSUE THREAD

**Issue by niamleeson** [ngrx/store#377]
If services for an angular app is set up to handle any actions by components, would this achieve something similar to what ngrx-store is doing? I would like to set up a fairly centralized layer for data storage and manipulation, but I would like my team to adjust to the new concept of having a centralized store quickly without having to learn RxJS, Redux's action creators, reducers and functional programming. If ngrx-store or ng-redux is still better choices, would someone please tell me some good supporting arguments as to why it is recommended to use them over services?

**Comment by fxck** [comment]
If you don't want your team to have to learn rxjs, don't use angular2 or ngrx/store, both rely heavily on observables and you'll be missing some of the most powerful features without utilising them. Otherwise [motivation](http://redux.js.org/docs/introduction/Motivation.html), and [three-principles](http://redux.js.org/docs/introduction/ThreePrinciples.html) and ["The introduction to Reactive Programming you've been missing"](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754) as well as many other articles and gists contain more than enough arguments as to why redux and rxjs are popular and why you should use them. As of comparison between ngrx/store and redux or ng-redux, read thru this [issue](https://github.com/ngrx/store/issues/16). 

And to answer your question, yes, you could set up a service that could catch actions. But then you'd "have" to deal with immutability. So you'd slowly build your own redux.. or relay.. or whatever state management lib is out there. But why would you ever want to do that when there are great a proven solutions in redux/ngrx with huge community and ecosystem around it.

**Comment by niamleeson** [comment]
Thank you for your reply. What is the most powerful feature that one would miss if they are not using ngrx/store? Just would like to know what the best argument for adopting ngrx/store is.

**Comment by fxck** [comment]
@ngrx/store is an rxjs stream, which means your ui will always reflect any changes to the state. You can use it along `async` pipe, which means you can turn off change detection for most of your components and gain big performance improvements. You can use great @ngrx/effects to handle any side effects of your action, as well as async calls. You should really read up on why rxjs is useful. And watch some videos, all the information you are looking for is already out there. 

https://www.youtube.com/watch?v=mhA7zZ23Odw

**Comment by niamleeson** [comment]
Ah that would be a good argument. I know RxJS is powerful but very difficult to understand. Took me 26 mini-practices of JsBin to understand most of the operators and subjects. I've already watched that video before but I feel like that video doesn't do justice on how powerful RxJS really is. The only cool feature was the time travel debugging which is extremely useful, but to get there, you need everyone in your team to learn RxJS, Functional programming and Redux

**Comment by kylecordes** [comment]
There is a trade-off:

* You could avoid both RxJS and Store, but we find this impractical and unrealistic for building any Angular application at scale. You will end up working much harder in writing lots of code to avoid these things. And probably sacrificing some degree of correctness along the way.
* You can skip Store (Redux) and go quite a long way with extensive use of RxJS for data flow. This really works very well, and I recommend it for some uses.
* As an application grows though, if you are only using homegrown RxJS base data flow for an application, eventually you probably find you are gradually reinventing aspects of Store / Redux.

Keeping all that in mind, if you are building a substantial application with Angular, why not use Store? 

Also possibly helpful, me talking about this stuff for 46 minutes. https://www.youtube.com/watch?v=eBLTz8QRg4Q

**Comment by derekkite** [comment]
You will need to write a service that provides a consistent and easy to change api to modify the data, you will need to come up with a fast and well tested way of querying the data, you will need to write and maintain observables for all your data. You will have to write and establish a pattern for async calls. You will have to write an api to access the data in your templates.

By the time you are done you will end up with something resembling ngrx. 

For a simple one service data, ngrx is overkill, lots of boilerplate, but for a reactive app with multiple data sources or complex data interactions across numerous developers having a well used library is really helpful.

**Comment by jotatoledo** [comment]
@kylecordes I just recently jumped into the ngrx train so Im more than happy to see some material like that! Your video is now on my "watch later" list

**Comment by BDominik** [comment]
@kylecordes thank you awesome video. :)
