### ISSUE TITLE
publishLast() & refCount() not working with state

### ISSUE THREAD

**Issue by Minh-Van** [ngrx/store#403]
Hi, I have an issue with ngrx/store when try to use `publishLast` & `refCount` in `rxjs 5.0.1`

I have a simple state as below
```
{
  queryStatus: '',
}
```
And I have a selector like that
```
get isQuerying$(): Observable<boolean> {
    return this._store.select(state => state.queryStatus)
    .map(status=> status === 'querying')
    .publishLast()
    .refCount();
  }
```
Then I write some code for test
```
isQuerying$.subscribe(result => console.log('Current Status: ', result));

updateStatus('querying'); // This function dispatch an action to update `queryStatus` in the state.
```
The result of my test is have no anything is logged in console. It seem I can not call `subscribe` from isQuerying$.
if I remove `publishLast` & `refCount` from `isQuerying$`, everything works well.

If this is not a bug, can you explain to me what's happened at there ?

**Comment by bfricka** [comment]
`publishLast` uses `AsyncSubject`. This essentially means it will emit the last value _when the observable completes`. Thus, you'll need to use something like `take` to actually get a value like this:

```ts
get isQuerying$(): Observable<boolean> {
  return this._store.select(state => state.queryStatus === 'querying')
    .take(1)
    .publishLast()
    .refCount();
}
```
Are you sure you're not looking for something more like `share` (which is just `.multicast(() => new Subject()).refCount()`?

Also note, you can get rid of `map` in this cast, since `select` (as you're using it) is just `.map().distinctUntilChanged()`
