### ISSUE TITLE
initial state in bootstrap

### ISSUE THREAD

**Issue by fxck** [ngrx/store#6]
Is there any reason you'd want to define initial state in `provideStore` in bootstrap? 

I mean handling the initial state in the [reducer](https://github.com/ngrx/store/blob/master/spec/fixtures/todos.ts#L32)(`INIT__STORE` fires, `switch` in all reducers ends in default, setting the state to [default parameter](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters) ).. makes more sense to me and it's [the way](http://redux.js.org/docs/basics/Reducers.html#handling-actions) redux is doing it as well.

**Comment by robwormald** [comment]
yep, the reasoning behind this is to do with Angular Universal apps - where the initial state of the app is rendered on the server.

Say you have a TodoList - where _server-side_ a fetch request is made to populate a list of todos. Angular Universal would render the initial list, and pass along the (JS) list of Todos so that they could be "re-connected" on the client-side without triggering a re-render.

**Comment by meenie** [comment]
Also, it seems there is no reason to have default param values in the reducers because they get overwritten by the `provideStore` function anyway.

**Comment by robwormald** [comment]
the issue here is partly to do with the `.scan()` operator in Rx, since if you don't provide an initial state, it uses the first value to come down the pipe - it doesn't know anything about default params. 

open to suggestions here, but I haven't yet found a solution I love.

**Comment by robwormald** [comment]
added the ability to use the reducer's default state in https://github.com/ngrx/store/commit/d67b96f48ad82b96a51150c04c9b6d94aecdaec7
