### ISSUE TITLE
typing of store.select(string)

### ISSUE THREAD

**Issue by kylecordes** [ngrx/store#60]
The typing of this method is rather unusual. You first parameterize the type of the store, with the type of the thing you are planning to select out of it. But the actual things that comes out will depend on the string/etc. you pass to select. I know that this is approximately as things are with redux, so I'm not complaining about it, but I am wondering if there is some different way to shape this part of the API to be more nicely typesafe.

As I understand typescript is not all that popular in the react community from which redux emerged, but it is of course very popular with Angular 2, and we have found it very helpful especially as applications grow in size.

**Comment by robwormald** [comment]
i'm open to suggestion, but there's not really a clean way in typescript today to handle this. It's generic, so your typical usage should look like

``` typescript
class FooService {
  foos: Observable<Foo[]>;
  constructor(store:Store<AppStore>){
    this.foos = store.select('foos');
  }
}

```

which keeps both the flexibility of store, and gives consumers of the service type safety

**Comment by MikeRyanDev** [comment]
It is also worth mentioning that this is one of the major benefits of using a selector function instead of a string:

``` ts
class FooService {
  foos = this.store.select(s => s.foos);
  constructor(private store: Store<AppStore>){ }
}
```

**Comment by kylecordes** [comment]
I was about to write the same thing as Mike. I think the generic typing can be fixed to make what he wrong, work. Right now it is typed such that it always returns the same generic parameter as the Store itself, it needs to be typed to understand the type transformation in the select function. The string version could return Any.

At risk of stepping slightly farther from the redux API, I think it would be worth considering removing the string version, and declaring that the function version is most suitable for the Angular community where this tool will be used typically, where typescript is dominant. Those using ES5 or 2015 can still use the function version, and this will encourage type hygiene.

**Comment by MikeRyanDev** [comment]
> At risk of stepping slightly farther from the redux API, I think it would be worth considering removing the string version, and declaring that the function version is most suitable for the Angular community where this tool will be used typically, where typescript is dominant. Those using ES5 or 2015 can still use the function version, and this will encourage type hygiene.

I second this motion. Using a string selector feels like a bad practice to me.

**Comment by robwormald** [comment]
if the generic can be fixed, great, let's do that. I'm not dropping the string selector though - its probably my favorite part of the entire lib and i'll invoke creator veto powers :)

**Comment by kylecordes** [comment]
Mike - I did the last PR, you want to do this one? :-)

Rob -  How is the string any different from any other JavaScript identifier that gets put into a string, beyond the reach of type systems, re-factoring tools, etc.? In other words, what do you especially like about it?  I wonder if there is some way to support such a thing in a typesafe, toolable manner?

**Comment by robwormald** [comment]
I went back and looked at this, because it was bugging me, and I'm not sure there's actually an issue here.

Given this setup:
<img width="593" alt="screen shot 2016-03-09 at 1 33 35 am" src="https://cloud.githubusercontent.com/assets/534930/13630971/01e18b0a-e597-11e5-99bf-a672f938f3dd.png">

If you give it a selector function, as suggested above, then type information is computed exactly as i'd expect it to:
<img width="538" alt="screen shot 2016-03-09 at 1 35 22 am" src="https://cloud.githubusercontent.com/assets/534930/13631024/491ebf6a-e597-11e5-8847-0710f2b0c430.png">

It's a given that given a string, the `store.select('users')` method isn't going to be able to derive type information - you get back an `Observable<{}>` (which is typescript saying it can't derive the type information):
<img width="534" alt="screen shot 2016-03-09 at 1 33 14 am" src="https://cloud.githubusercontent.com/assets/534930/13630984/1cce3cce-e597-11e5-9f9b-f6b4746e465a.png">
Which is what I'd expect.

So both the string case and the selector case work as well as can be reasonably expected. If I prefer the string case, I simply have to tell typescript what the type is:

<img width="456" alt="screen shot 2016-03-09 at 1 38 40 am" src="https://cloud.githubusercontent.com/assets/534930/13631120/d86e9bc2-e597-11e5-80ef-5f040a6751a9.png">

And downstream, all type information propagates properly:
<img width="476" alt="screen shot 2016-03-09 at 1 39 32 am" src="https://cloud.githubusercontent.com/assets/534930/13631142/ee1a8d28-e597-11e5-8123-69313f604949.png">
<img width="719" alt="screen shot 2016-03-09 at 1 39 48 am" src="https://cloud.githubusercontent.com/assets/534930/13631143/ee1c98fc-e597-11e5-962e-5c9bd50072a1.png">

So - unless I'm missing something, I don't see a functional problem here. If you prefer the selector method, that works, if you prefer the string method, that works as well. It requires precisely one manual type annotation, and everything that consumes it works as expected. 

I consider store like http - its not a thing you want to be injecting directly into components in a real-world application - you'll want to slice off the appropriate piece of state and expose it via a service, which by the way, you're going to have to give a type definition to _anyway_ - and at that point, the practical difference is nil:
<img width="461" alt="screen shot 2016-03-09 at 1 50 11 am" src="https://cloud.githubusercontent.com/assets/534930/13631409/59199c6c-e599-11e5-9a82-9df80ec56174.png">

If you're advocating dropping the string case because of a belief that if the type information can't be computed, it shouldn't be usable, then I fundamentally disagree - Typescript is still Javascript, in all it's dynamically typed glory, and the ability to be meta with this sort of stuff is exactly _why_ I'm a javascript developer. 

/rant.

**Comment by wmaurer** [comment]
@robwormald Whilst I completely agree with your argument, and think it's fine to leave the string selector as it is, what I still haven't really understood is why one would prefer the string selector over the selector function. I think an explanation of this would help users who are new to ngrx.

EDIT: I see @kylecordes is asking the same [question](https://github.com/ngrx/store/issues/60#issuecomment-193605134)

**Comment by kylecordes** [comment]
@robwormald I also worked with the typing for a while last night, and found you are correct above. It is typed correctly. I had been incorrectly typing my store as I injected it, which I had done because I have not created the equivalent of your AppStore interface above. I was doing it the way shown in the README, a line of code there:

```
constructor(public store: Store<number>){
```

...gives the incorrect impression that this is a reasonable way to type the store this way at the point of injection. This line of code is wrong; the actual type of the store is an interface (missing from the example in the readme) of the overall type, such that each field and that overall type matches both the name and type of a reducer.

I think it is important to document this clearly in the readme and elsewhere, that the only way to correctly type a store is to create an interface whose fields and types exactly match the reducers you are supplying. The documentation should discourage mistyping the store itself even when using a string selector. In that scenario, the select operation itself can supply the type that the string corresponds to.

```
select<TypeIWant>("stringNameOfTheAppStateFieldWithThatType").
```

**Comment by robwormald** [comment]
I've updated the readme to correct the type interface

**Comment by tlong-dev** [comment]
I'm new to ngrx and just trying to research how it will play with Typescript.

Has anyone considered typing `select()` using the new `keyof` feature of TS?
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html

This may enable some string validation.
