### ISSUE TITLE
restructure npm distribution

### ISSUE THREAD

**Issue by robwormald** [ngrx/store#65]
TODO: publish only the dist folder and copy package.json to it before publishing to simplify config

**Comment by kylecordes** [comment]
As part of this change, how about shipping a SystemJS bundle in there, akin to the bundles provided by Angular 2, RxJS, etc? This would make it especially easy to consume NgRx in projects that otherwise just need those bundles. (For projects that can live without much build compelxity complexity, it is blissfully fast to operate with just SystemJS, command line tsc set to output a SystemJS bundle, and a web server... no JSPM, no Grunt, no Gulp, no Webpack, ...).

**Comment by robwormald** [comment]
This is done already
