### ISSUE TITLE
Async pipe on object instead of sequence

### ISSUE THREAD

**Issue by pauleveritt** [ngrx/store#91]
I'm sure this is less a bug report and more a "You're holding it wrong"...I have a very simple usage with an [Observable being referenced in a template](https://gist.github.com/pauleveritt/a86ccbe510bb754107354274dfae9052). 

However, the value displayed never changes. If I .subscribe to the Observable, I see that it gets updated. If I spelunk into what the template is handed, it isn't the ICounter object, it's a Subject.

**Comment by fxck** [comment]
try 

```
{{ ( counter | async)?.value }}
```

**Comment by pauleveritt** [comment]
@fxck Thanks so much for that, it worked. I haven't seen that construct much, which makes me wonder, am I thinking about it in a wrong fashion?

Also, I have a second question related to combineLatest. I think you'd prefer questions in Gitter, is that correct?

**Comment by fxck** [comment]
it's just elvis operator, meaning you can reference things that do not yet exist, and yes, gitter is generally better for questions

**Comment by fxck** [comment]
also you don't see it much, because you generally want to follow the smart / dumb component approach, the smart one gets slice of the store https://github.com/fxck/ngrx-example/blob/master/src/app/_people/routes/people.detail.route/people.detail.route.ts#L31

passed it down to the dumb one 
https://github.com/fxck/ngrx-example/blob/master/src/app/_people/routes/people.detail.route/people.detail.route.html#L3

in which you can then use it without having to worry whether it exists or not(it will) https://github.com/fxck/ngrx-example/blob/master/src/app/_people/components/person-detail.component/person-detail.component.html#L1

**Comment by pauleveritt** [comment]
@fxck I should have mentioned, I was working on an article showing converting the Tour of Heroes final step, to ngrx/store. In the last step, they show moving the Heroes from an input to a service.

**Comment by robwormald** [comment]
Closing as solved. Feel free to continue discussion.

**Comment by smkamranqadri** [comment]
it's working but what for the else case what to show 'Not Loaded' till async resolve.

{{ ( counter | async)?.value }}
